### ISSUE TITLE
Ember 4.8.0 Compatibility

### ISSUE THREAD

**Issue by nova-alex** [postedin/ember-ckeditor#23]
Loving this package and trying to install on a brand new installation of [Ember 4.8 (CLI)](https://github.com/ember-cli/ember-cli/releases/tag/v4.8.0)

Running into an issue with `@glimmer/manager.js` ~line 825

``` javascript
function modifierCapabilities(managerAPI, optionalFeatures) {
    if (optionalFeatures === void 0) {
      optionalFeatures = {};
    }

    if (true
    /* DEBUG */
    && managerAPI !== '3.22') { // << Error here, managerAPI is 3.13
      throw new Error('Invalid modifier manager compatibility specified');
    }

    return buildCapabilities({
      disableAutoTracking: Boolean(optionalFeatures.disableAutoTracking)
    });
  }
``` 

Seems to be a version mismatch with `@ember/render-modifiers`

Upgrading to `"@ember/render-modifiers": "^2.0.4"` seems to do the trick .. but I'm not really set up to test whether this fix is viable for release.

Any advice would be appreciated. I've created a fork of ember-ckeditor and using that in the meantime.

**Comment by robclancy** [comment]
I'm going to update 0.x to be some better dependencies etc. Then make 1.x with latest addon blueprints and dependencies along with removing the need for render-modifiers at all (I think this recommended now). Then 2.x with embroider and work out a basic demo site I guess.

**Comment by robclancy** [comment]
1.0.0 now works with 4.4 and should with 4.8. When I get a chance I'll be writing proper tests for 1.x. Then a complete rewrite for 2.x.

**Comment by nova-alex** [comment]
This is super helpful and I sincerely appreciate everything you've done with this addon.
